title: SynEdu
author: Tieu Long Phan
logo: _static/synedu_logo_square_icon_transparent.png

execute:
  execute_notebooks: "off"

only_build_toc_files: false

repository:
  url: https://github.com/TieuLongPhan/SynEdu
  path_to_book: docs
  branch: main

html:
  favicon: _static/synedu_logo_square_icon_transparent.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx
  config:
    exclude_patterns:
      - _build
      - Thumbs.db
      - .DS_Store
      - "**.ipynb_checkpoints"
      - README.md
    autosummary_generate: true
    napoleon_google_docstring: false
    napoleon_use_param: false
    napoleon_use_ivar: true
    myst_all_links_external: true
    suppress_warnings:
      - etoc.toctree
      - myst.xref_missing
      - ref.myst
      - misc.highlighting_failure
    intersphinx_mapping:
      python:
        - https://docs.python.org/3
        - null
      networkx:
        - https://networkx.org/documentation/stable/
        - null
    html_show_sourcelink: false
    html_theme_options:
      navigation_with_keys: true
      show_navbar_depth: 2
      use_download_button: false
